// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RehabilitationSystem.Data;

#nullable disable

namespace RehabilitationSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "4ae12bc1-e040-48fc-9515-f5a1a016cd31",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "8bd9ff84-03fe-4406-9701-286dec855ca8",
                            Name = "Therapist",
                            NormalizedName = "THERAPIST"
                        },
                        new
                        {
                            Id = "b9a9fcc6-c05e-42b8-9631-585dd1f404dc",
                            Name = "CustomerService",
                            NormalizedName = "CUSTOMERSERVICE"
                        },
                        new
                        {
                            Id = "1f3cffed-0351-4f88-a2a5-ec4fb9d028b4",
                            Name = "Parent",
                            NormalizedName = "PARENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RehabilitationSystem.Models.Admin", b =>
                {
                    b.Property<string>("AdminId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminId");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            AdminId = "admin1",
                            AppUserId = "user1",
                            Name = "Admin One"
                        });
                });

            modelBuilder.Entity("RehabilitationSystem.Models.Announcement", b =>
                {
                    b.Property<string>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AdminId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Date")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Status")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnnouncementId");

                    b.HasIndex("AdminId");

                    b.ToTable("Announcements");

                    b.HasData(
                        new
                        {
                            AnnouncementId = "announcement1",
                            AdminId = "admin1",
                            Content = "Content of Announcement One",
                            Date = new DateTime(2024, 6, 1, 22, 46, 55, 68, DateTimeKind.Local).AddTicks(4285),
                            Status = true,
                            Title = "Announcement One"
                        });
                });

            modelBuilder.Entity("RehabilitationSystem.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "user1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4365f877-2d0e-4acf-acd0-2ca571cf0c5c",
                            Email = "admin1@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN1@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN1",
                            PasswordHash = "AQAAAAIAAYagAAAAEGvSp2DAFwND3sIGfF0yoKbvX6/DcwqeWEVzd93ioGQrO6WEjwI+cvT0Isvw7yZELA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2511b64d-82c2-4e8d-8149-01578e1f6351",
                            TwoFactorEnabled = false,
                            UserName = "admin1"
                        },
                        new
                        {
                            Id = "user2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0d4f4aa6-313c-42b4-bd9e-66d6051baec2",
                            Email = "therapist1@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "THERAPIST1@EXAMPLE.COM",
                            NormalizedUserName = "THERAPIST1",
                            PasswordHash = "AQAAAAIAAYagAAAAEBK3ODLlYAEAVflRa4NXWANT3Sn7lWbTAdlUk4CGWE9bx2p5LDqErzAggRXz0G2FMQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ee576314-b972-4510-8d53-631e3efef285",
                            TwoFactorEnabled = false,
                            UserName = "therapist1"
                        },
                        new
                        {
                            Id = "user3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2fbb288d-2664-4a24-b88d-7b316b0abb6e",
                            Email = "customerService1@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "CUSTOMERSERVICE1@EXAMPLE.COM",
                            NormalizedUserName = "CUSTOMERSERVICE1",
                            PasswordHash = "AQAAAAIAAYagAAAAEOqHciQRsU8gRKz/mJnN24XvtVYipcMFRGO/zWrUHM6VDGeoy5TKA3xbQQiKEEkiPQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fa957701-c2fc-47c4-92e8-cc7f98a3678d",
                            TwoFactorEnabled = false,
                            UserName = "customerService1"
                        },
                        new
                        {
                            Id = "user4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0f31e78d-8357-4729-bdea-d2439941a022",
                            Email = "parent1@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "PARENT1@EXAMPLE.COM",
                            NormalizedUserName = "PARENT1",
                            PasswordHash = "AQAAAAIAAYagAAAAEEOXLXdFTwmeRZEutE4hOO/5FkfZIZKQRDUcKTWfxuyfSqxbAskmsxvPVe0gxOA5aA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8a3e23c5-99de-432a-8d3b-ee294e9cda40",
                            TwoFactorEnabled = false,
                            UserName = "parent1"
                        });
                });

            modelBuilder.Entity("RehabilitationSystem.Models.Billing", b =>
                {
                    b.Property<string>("BillingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("IssueDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<string>("ProgramId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProgramStudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("TotalPayAmount")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BillingId");

                    b.HasIndex("ProgramId");

                    b.HasIndex("StudentId");

                    b.ToTable("Billings");

                    b.HasData(
                        new
                        {
                            BillingId = "billing1",
                            IssueDate = new DateTime(2024, 6, 1, 22, 46, 55, 68, DateTimeKind.Local).AddTicks(3934),
                            PaymentStatus = false,
                            ProgramStudentId = "programStudent1",
                            TotalPayAmount = 200.0m
                        });
                });

            modelBuilder.Entity("RehabilitationSystem.Models.BillingItem", b =>
                {
                    b.Property<string>("BillingItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Amount")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("BillingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BillingItemId");

                    b.HasIndex("BillingId");

                    b.ToTable("BillingItems");

                    b.HasData(
                        new
                        {
                            BillingItemId = "billingItem1",
                            Amount = 4,
                            BillingId = "billing1",
                            Description = "Billing Item One",
                            Price = 50.0m
                        });
                });

            modelBuilder.Entity("RehabilitationSystem.Models.CustomerService", b =>
                {
                    b.Property<string>("CustomerServiceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerServiceId");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("CustomerServices");

                    b.HasData(
                        new
                        {
                            CustomerServiceId = "customerService1",
                            AppUserId = "user3",
                            Name = "Customer Service One"
                        });
                });

            modelBuilder.Entity("RehabilitationSystem.Models.Parent", b =>
                {
                    b.Property<string>("ParentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ParentId");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("Parents");

                    b.HasData(
                        new
                        {
                            ParentId = "parent1",
                            Address = "123 Street",
                            AppUserId = "user4",
                            City = "City",
                            Name = "Parent One",
                            Occupation = "Occupation",
                            Postcode = "12345",
                            State = "State"
                        });
                });

            modelBuilder.Entity("RehabilitationSystem.Models.Program", b =>
                {
                    b.Property<string>("ProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProgramId");

                    b.ToTable("Programs");

                    b.HasData(
                        new
                        {
                            ProgramId = "program1",
                            Description = "Description One",
                            Name = "Program One",
                            Objective = "Objective One",
                            Price = 100.0m
                        });
                });

            modelBuilder.Entity("RehabilitationSystem.Models.ProgramStudent", b =>
                {
                    b.Property<string>("ProgramStudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProgramId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("RegisterDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProgramStudentId");

                    b.HasIndex("ProgramId");

                    b.HasIndex("StudentId");

                    b.ToTable("ProgramStudents");

                    b.HasData(
                        new
                        {
                            ProgramStudentId = "programStudent1",
                            ProgramId = "program1",
                            RegisterDate = new DateTime(2024, 6, 1, 22, 46, 55, 68, DateTimeKind.Local).AddTicks(3455),
                            StudentId = "student1"
                        });
                });

            modelBuilder.Entity("RehabilitationSystem.Models.ProgramStudentSlot", b =>
                {
                    b.Property<string>("ProgramStudentSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProgramStudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SlotId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProgramStudentSlotId");

                    b.HasIndex("ProgramStudentId");

                    b.HasIndex("SlotId");

                    b.ToTable("ProgramStudentSlots");

                    b.HasData(
                        new
                        {
                            ProgramStudentSlotId = "ProgramStudentSlot1",
                            ProgramStudentId = "programStudent1",
                            SlotId = "slot1"
                        });
                });

            modelBuilder.Entity("RehabilitationSystem.Models.Report", b =>
                {
                    b.Property<string>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramStudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TherapistId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReportId");

                    b.HasIndex("TherapistId");

                    b.HasIndex("ProgramStudentId", "TherapistId")
                        .IsUnique();

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            ReportId = "report1",
                            Content = "Content of Report One",
                            ProgramStudentId = "programStudent1",
                            TherapistId = "therapist1",
                            Title = "Report One"
                        });
                });

            modelBuilder.Entity("RehabilitationSystem.Models.Session", b =>
                {
                    b.Property<string>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SessionId");

                    b.HasIndex("ProgramId");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            SessionId = "session1",
                            Description = "Description One",
                            Name = "Session One",
                            ProgramId = "program1"
                        });
                });

            modelBuilder.Entity("RehabilitationSystem.Models.Slot", b =>
                {
                    b.Property<string>("SlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("EndTime")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartTime")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("TherapistSessionId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SlotId");

                    b.HasIndex("TherapistSessionId");

                    b.ToTable("Slots");

                    b.HasData(
                        new
                        {
                            SlotId = "slot1",
                            EndTime = new DateTime(2024, 6, 2, 0, 46, 55, 68, DateTimeKind.Local).AddTicks(3694),
                            StartTime = new DateTime(2024, 6, 1, 23, 46, 55, 68, DateTimeKind.Local).AddTicks(3614),
                            TherapistSessionId = "therapistSession1"
                        });
                });

            modelBuilder.Entity("RehabilitationSystem.Models.Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Age")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DOB")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("StudentId");

                    b.HasIndex("ParentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = "student1",
                            Age = 10,
                            DOB = new DateTime(2014, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = 0,
                            Name = "Student One",
                            ParentId = "parent1"
                        });
                });

            modelBuilder.Entity("RehabilitationSystem.Models.Therapist", b =>
                {
                    b.Property<string>("TherapistId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TherapistId");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("Therapists");

                    b.HasData(
                        new
                        {
                            TherapistId = "therapist1",
                            AppUserId = "user2",
                            Name = "Therapist One"
                        });
                });

            modelBuilder.Entity("RehabilitationSystem.Models.TherapistSession", b =>
                {
                    b.Property<string>("TherapistSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TherapistId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TherapistSessionId");

                    b.HasIndex("SessionId");

                    b.HasIndex("TherapistId", "SessionId")
                        .IsUnique();

                    b.ToTable("TherapistSessions");

                    b.HasData(
                        new
                        {
                            TherapistSessionId = "therapistSession1",
                            SessionId = "session1",
                            TherapistId = "therapist1"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("RehabilitationSystem.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("RehabilitationSystem.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RehabilitationSystem.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("RehabilitationSystem.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RehabilitationSystem.Models.Admin", b =>
                {
                    b.HasOne("RehabilitationSystem.Models.AppUser", "AppUser")
                        .WithOne("Admin")
                        .HasForeignKey("RehabilitationSystem.Models.Admin", "AppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("RehabilitationSystem.Models.Announcement", b =>
                {
                    b.HasOne("RehabilitationSystem.Models.Admin", "Admin")
                        .WithMany("Announcements")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("RehabilitationSystem.Models.Billing", b =>
                {
                    b.HasOne("RehabilitationSystem.Models.Program", null)
                        .WithMany("Billings")
                        .HasForeignKey("ProgramId");

                    b.HasOne("RehabilitationSystem.Models.Student", null)
                        .WithMany("Billings")
                        .HasForeignKey("StudentId");
                });

            modelBuilder.Entity("RehabilitationSystem.Models.BillingItem", b =>
                {
                    b.HasOne("RehabilitationSystem.Models.Billing", "Billing")
                        .WithMany("BillingItems")
                        .HasForeignKey("BillingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Billing");
                });

            modelBuilder.Entity("RehabilitationSystem.Models.CustomerService", b =>
                {
                    b.HasOne("RehabilitationSystem.Models.AppUser", "AppUser")
                        .WithOne("CustomerService")
                        .HasForeignKey("RehabilitationSystem.Models.CustomerService", "AppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("RehabilitationSystem.Models.Parent", b =>
                {
                    b.HasOne("RehabilitationSystem.Models.AppUser", "AppUser")
                        .WithOne("Parent")
                        .HasForeignKey("RehabilitationSystem.Models.Parent", "AppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("RehabilitationSystem.Models.ProgramStudent", b =>
                {
                    b.HasOne("RehabilitationSystem.Models.Program", "Program")
                        .WithMany("ProgramStudents")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RehabilitationSystem.Models.Billing", "Billing")
                        .WithOne("ProgramStudent")
                        .HasForeignKey("RehabilitationSystem.Models.ProgramStudent", "ProgramStudentId")
                        .HasPrincipalKey("RehabilitationSystem.Models.Billing", "ProgramStudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RehabilitationSystem.Models.Student", "Student")
                        .WithMany("ProgramStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Billing");

                    b.Navigation("Program");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("RehabilitationSystem.Models.ProgramStudentSlot", b =>
                {
                    b.HasOne("RehabilitationSystem.Models.ProgramStudent", "ProgramStudent")
                        .WithMany("ProgramStudentSlots")
                        .HasForeignKey("ProgramStudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RehabilitationSystem.Models.Slot", "Slot")
                        .WithMany("ProgramStudentSlots")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgramStudent");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("RehabilitationSystem.Models.Report", b =>
                {
                    b.HasOne("RehabilitationSystem.Models.ProgramStudent", "ProgramStudent")
                        .WithMany("Reports")
                        .HasForeignKey("ProgramStudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RehabilitationSystem.Models.Therapist", "Therapist")
                        .WithMany("Reports")
                        .HasForeignKey("TherapistId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProgramStudent");

                    b.Navigation("Therapist");
                });

            modelBuilder.Entity("RehabilitationSystem.Models.Session", b =>
                {
                    b.HasOne("RehabilitationSystem.Models.Program", "Program")
                        .WithMany("Sessions")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("RehabilitationSystem.Models.Slot", b =>
                {
                    b.HasOne("RehabilitationSystem.Models.TherapistSession", "TherapistSession")
                        .WithMany("Slots")
                        .HasForeignKey("TherapistSessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("TherapistSession");
                });

            modelBuilder.Entity("RehabilitationSystem.Models.Student", b =>
                {
                    b.HasOne("RehabilitationSystem.Models.Parent", "Parent")
                        .WithMany("Students")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("RehabilitationSystem.Models.Therapist", b =>
                {
                    b.HasOne("RehabilitationSystem.Models.AppUser", "AppUser")
                        .WithOne("Therapist")
                        .HasForeignKey("RehabilitationSystem.Models.Therapist", "AppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("RehabilitationSystem.Models.TherapistSession", b =>
                {
                    b.HasOne("RehabilitationSystem.Models.Session", "Session")
                        .WithMany("TherapistsSessions")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RehabilitationSystem.Models.Therapist", "Therapist")
                        .WithMany("TherapistSessions")
                        .HasForeignKey("TherapistId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("Therapist");
                });

            modelBuilder.Entity("RehabilitationSystem.Models.Admin", b =>
                {
                    b.Navigation("Announcements");
                });

            modelBuilder.Entity("RehabilitationSystem.Models.AppUser", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("CustomerService");

                    b.Navigation("Parent");

                    b.Navigation("Therapist");
                });

            modelBuilder.Entity("RehabilitationSystem.Models.Billing", b =>
                {
                    b.Navigation("BillingItems");

                    b.Navigation("ProgramStudent");
                });

            modelBuilder.Entity("RehabilitationSystem.Models.Parent", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("RehabilitationSystem.Models.Program", b =>
                {
                    b.Navigation("Billings");

                    b.Navigation("ProgramStudents");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("RehabilitationSystem.Models.ProgramStudent", b =>
                {
                    b.Navigation("ProgramStudentSlots");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("RehabilitationSystem.Models.Session", b =>
                {
                    b.Navigation("TherapistsSessions");
                });

            modelBuilder.Entity("RehabilitationSystem.Models.Slot", b =>
                {
                    b.Navigation("ProgramStudentSlots");
                });

            modelBuilder.Entity("RehabilitationSystem.Models.Student", b =>
                {
                    b.Navigation("Billings");

                    b.Navigation("ProgramStudents");
                });

            modelBuilder.Entity("RehabilitationSystem.Models.Therapist", b =>
                {
                    b.Navigation("Reports");

                    b.Navigation("TherapistSessions");
                });

            modelBuilder.Entity("RehabilitationSystem.Models.TherapistSession", b =>
                {
                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
